# Generated by Django 6.0.5 on 2026-06-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_no', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
