# Generated by Django 6.0.5 on 2026-06-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('fee', models.DecimalField(decimal_places=1, max_digits=5)),
                ('created_at', models.DateField()),
                ('sub', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
